name: CI/CD Pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-python@v4
      #- uses: iterative/setup-cml@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Respiratory Analysis
        run: |
          python Exploration/inference.py \
            --diagnosis_file './data/Respiratory_Sound_Database/patient_diagnosis.csv' \
            --audio_path './data/Respiratory_Sound_Database/testsample'

          