name: CI/CD Pipeline
on: [push]

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  respiratory-analysis:
    name: Respiratory Analysis
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Respiratory Analysis
        run: |
          python Exploration/inference.py \
            --diagnosis_file './data/Respiratory_Sound_Database/patient_diagnosis.csv' \
            --audio_path './data/Respiratory_Sound_Database/testsample'

  training-code:
    name: Run and Test Training Code
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Training Code
        run: |
          python Training/train.py --debug
          