name: CI/CD Pipeline
on: [push]

jobs:
  respiratory-analysis:
    name: Respiratory Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Respiratory Analysis
        run: |
          python Exploration/inference.py \
            --diagnosis_file './data/Respiratory_Sound_Database/patient_diagnosis.csv' \
            --audio_path './data/Respiratory_Sound_Database/testsample'

  training-code:
    name: Run and Test Training Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Code
        run: |
          python LegacyTraining/train.py --debug

  single-fileinference-code:
    name: Test the Trained Models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Testing Code on a Sample File
        run: |
          python Model_Inference.py

  out-of-bag-testing-code:
    name: Test the Trained Models with Unseen Testing Set
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Testing Code on an Unseen Testing Set
        run: |
          python TestModels.py
