name: CI/CD Pipeline
on: [push]

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Save Python Dependencies
        run: tar -czf dependencies.tar.gz ~/.cache/pip
        # Upload the dependencies as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: dependencies.tar.gz

  respiratory-analysis:
    name: Respiratory Analysis
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Dependencies
        uses: actions/download-artifact@v3
        with:
          name: dependencies

      - name: Extract Dependencies
        run: tar -xzf dependencies.tar.gz -C ~/

      - name: Run Respiratory Analysis
        run: |
          python Exploration/inference.py \
            --diagnosis_file './data/Respiratory_Sound_Database/patient_diagnosis.csv' \
            --audio_path './data/Respiratory_Sound_Database/testsample'

  training-code:
    name: Run and Test Training Code
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Dependencies
        uses: actions/download-artifact@v3
        with:
          name: dependencies

      - name: Extract Dependencies
        run: tar -xzf dependencies.tar.gz -C ~/

      - name: Run Training Code
        run: |
          python LegacyTraining/train.py --debug

  single-fileinference-code:
    name: Test the trained models
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Dependencies
        uses: actions/download-artifact@v3
        with:
          name: dependencies

      - name: Extract Dependencies
        run: tar -xzf dependencies.tar.gz -C ~/

      - name: Run Testing Code on a sample file
        run: |
          python Model_Inference.py 

  out-of-bag-testing-code:
    name: Test the trained models with Unseen Testing Set
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Dependencies
        uses: actions/download-artifact@v3
        with:
          name: dependencies

      - name: Extract Dependencies
        run: tar -xzf dependencies.tar.gz -C ~/

      - name: Run testing code on an unseen testing cet
        run: |
          python TestModels.py 
                                        